	LJMP ;AD 16
	ALJMP ;AD 11
	SLJMP ; 
	JMP A +DPTR; A - ACCUMU
	JZ ; IF ACCUMU = 0
	JNZ ; IF ACCUMU !=0
	JC ; 
	JNC; BIT C  != 0
	JBC BIT + SHIFT; IF THIS BIT; INVERTS BIT
	
	DJNZ RN, LABEL; LOOP
	DJNZ ADDRESS, LABEL;
	; COMPARING
	CJNEA  ADDRESS, SHIFT
	CJNEA NUMBER
	CJNERD R(0 OR 1)??
	; CALL AND RETURN
	LCALL ADDRESS16
	ACALL ADDRESS11
	RET
	RETI
	NOPE; EMPTY COMMAND

SWAP BANKS 2 AND 3	
	 