# Generated by Django 3.0.11 on 2021-01-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Глобальный текст',
                'verbose_name_plural': 'Глобальный текст',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='main.Text', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Refences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refences', to='main.Text', verbose_name='Текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Индефикатор пользователя')),
            ],
            options={
                'verbose_name': 'Обращения граждан',
                'verbose_name_plural': 'Обращения граждан',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.Text', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.Text', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Анонс мероприятия',
                'verbose_name_plural': 'Анонсы мероприятий',
                'ordering': ['-date'],
            },
        ),
    ]
